title: "Shelley Salinas Photography"
email: shelleysalinas@icloud.com
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
url: https://shells14.github.io 
permalink: "/:title/"
excerpt_separator: "<!--more-->" #added this to chnage where plog post shows excerpt (preview of log post)
logo: 'assets/images/ShelleySalinasLogoFixed.png'
favicon: 'assets/images/favicon.ico'
author: Shelley Salinas
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  input: GFM
  hard_wrap: false
  parse_block_html: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1
include:
  - assets/pdf


# Authors
authors:
  Shelley Salinas:
    name: Shelley Salinas
    display_name: Shelley Salinas
    avatar: 'assets/images/ShelleyAuthorImage.png'
    email: shelleysalinas@icloud.com
    instagram: https://www.instagram.com/shelleycarretophotography/
    description: "Creator of Life Captured, Gratitude Preserved, Photographer, Student and Observer."
  Stacy:
    name: Stacy Airam
    display_name: Stacy Airam
    avatar: 'assets/images/stacyAuthor.png'
    email: Stacysalinasc@gmail.com
    description: Stacy is a contributing writer to this post, offering her reflections and perspective on the moment captured.
  Emma:
    name: Emma Carne
    display_name: Emma Carne
    avatar: 'assets/images/emmaportrait.png'
    email: emmaacarne@gmail.com
    description: Emma is a contributing writer to this post, offering her reflections and perspective on the moment captured.
  Jake:
    name: Jake Downey
    display_name: Jake Downey
    avatar: 'assets/images/jakeportrait.png'
    email: jakedowney21@gmail.com
    description: Jake is a contributing writer to this post, offering his reflections and perspective on the moment captured.
  Ashley:
    name: Ashley Salinas
    display_name: Ashley Salinas
    avatar: 'assets/images/ashleyportrait.png'
    email: ashleycarreto4@gmail.com
    description: Ashley is a contributing writer to this post, offering her reflections and perspective on the moment captured.
  Kyla:
    name: Kyla Romachyk
    display_name: Kyla Romachyk
    avatar: 'assets/images/kylaportrait.png'
    email: kylaromanchyk@gmail.com
    description: Kyla is a contributing writer to this post, offering her reflections and perspective on the moment captured.
  Buse:
    name: Buse Ekmen
    display_name: Buse Ekmen
    avatar: 'assets/images/buseportrait.png'
    instagram: https://www.instagram.com/buse.creates/
    email: bekmen@uoguelph.ca
    description: Buse is a contributing writer to this post, offering her reflections and perspective on the moment captured.


# Social
social:
  instagram: https://www.instagram.com/shelleycarretophotography/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives